import Head from "next/head";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";

import TopNavComponent from "./../components/Layouts/TopNavComponent";
import About from "./About";
import Experience from './../components/Experience/Experience';
import Projects from './../components/projects/Projects';
import Footer from "../components/Layouts/Footer";
import ContactMe from "../components/Layouts/ContactMe";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const handleClick = () => {
    setDarkMode(!darkMode);
  };
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mohamed Magdy Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="  px-10 min-h-screen dark:bg-gray-900 md:px-10 lg:px-20">
        <TopNavComponent handleClick={handleClick} />
        
          {/* <Skills /> */}
          <Experience />
          {/* <About /> */}
        <Projects />
        <ContactMe />
        <Footer />
      </main>
    </div>
  );
}
